# Generated by Django 4.1.7 on 2023-03-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipez', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bookmark',
            field=models.JSONField(null=True),
        ),
    ]
