# Generated by Django 4.1.7 on 2023-03-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipez', '0002_alter_userprofile_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
