# Generated by Django 4.1.7 on 2023-03-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipez', '0004_rename_name_ingredient_name_and_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name_and_amount',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='region',
            field=models.CharField(default='unknown', max_length=128),
        ),
    ]
