# Generated by Django 4.1.7 on 2023-03-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipez', '0005_alter_ingredient_name_and_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='recipez.ingredient'),
        ),
    ]
