# Generated by Django 4.1.7 on 2023-03-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipez', '0006_remove_ingredient_recipes_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(default='None', max_length=128),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='recipez.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='region',
            field=models.CharField(default='None', max_length=128),
        ),
    ]
