# Generated by Django 4.1.7 on 2023-03-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipez', '0007_alter_recipe_category_alter_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_recipes', to='recipez.userprofile'),
        ),
    ]
